services:

  shinysim:
  
    build: 
      context: .
      dockerfile: Dockerfile

    ports: 
      - "3000:3000"
    volumes: 
      - .:/app
      - /app/node_modules
      - /app/src/api

    command: npm run container
